/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.blau.android;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int bridleway=0x7f05000f;
        public static final int building=0x7f050016;
        public static final int ccc_beige=0x7f050002;
        public static final int ccc_darkred=0x7f050001;
        public static final int ccc_ocher=0x7f050004;
        public static final int ccc_red=0x7f050000;
        public static final int ccc_white=0x7f050003;
        public static final int college=0x7f050018;
        public static final int commercial=0x7f05001c;
        public static final int cycleway=0x7f05000d;
        public static final int footway=0x7f05000e;
        public static final int forest=0x7f05001a;
        public static final int grey=0x7f050005;
        public static final int halt=0x7f050014;
        public static final int leisure=0x7f050017;
        public static final int motorway=0x7f050007;
        public static final int parking=0x7f050019;
        /**  
	<color name="unclassified">#FFFFFF</color>
	<color name="residential">#FFFFFF</color>
	<color name="living_street">#FFFFFF</color>
	<color name="service">#FFFFFF</color>

         */
        public static final int pedestrian=0x7f05000c;
        public static final int power=0x7f050015;
        public static final int primary=0x7f050009;
        public static final int retail=0x7f05001b;
        public static final int river=0x7f050011;
        public static final int secondary=0x7f05000a;
        public static final int station=0x7f050013;
        public static final int stroke=0x7f050006;
        public static final int tertiary=0x7f05000b;
        public static final int tracktype=0x7f050010;
        public static final int tram=0x7f050012;
        public static final int trunk=0x7f050008;
        public static final int water=0x7f05001d;
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int menu_add=0x7f020001;
        public static final int menu_append=0x7f020002;
        public static final int menu_edit=0x7f020003;
        public static final int menu_erase=0x7f020004;
        public static final int menu_move=0x7f020005;
        public static final int menu_tag=0x7f020006;
        public static final int osm_logo=0x7f020007;
        /**  copied 
         */
        public static final int screen_background_black=0x7f020008;
        public static final int translucent_background=0x7f020009;
        public static final int transparent_background=0x7f02000a;
    }
    public static final class id {
        public static final int location_button_current=0x7f08000b;
        public static final int location_button_no_location=0x7f08000c;
        public static final int location_coordinates=0x7f080005;
        public static final int location_coordinates_layout=0x7f080006;
        public static final int location_current=0x7f080003;
        public static final int location_last=0x7f080002;
        public static final int location_lat_edit=0x7f080007;
        public static final int location_lon_edit=0x7f080008;
        public static final int location_map=0x7f080004;
        public static final int location_radius_seeker=0x7f08000a;
        public static final int location_radius_text=0x7f080009;
        public static final int location_type=0x7f080000;
        public static final int location_type_group=0x7f080001;
        public static final int menu_add=0x7f080010;
        public static final int menu_append=0x7f080013;
        public static final int menu_confing=0x7f08001c;
        public static final int menu_edit=0x7f080011;
        public static final int menu_erase=0x7f080014;
        public static final int menu_gps_follow=0x7f080016;
        public static final int menu_gps_start_pause=0x7f080015;
        public static final int menu_gps_stop=0x7f080017;
        public static final int menu_gps_upload=0x7f080018;
        public static final int menu_move=0x7f08000f;
        public static final int menu_save=0x7f08001d;
        public static final int menu_tag=0x7f080012;
        public static final int menu_transfer_download_current=0x7f080019;
        public static final int menu_transfer_download_other=0x7f08001a;
        public static final int menu_transfer_upload=0x7f08001b;
        public static final int okButton=0x7f08000e;
        public static final int tag_menu_mapfeatures=0x7f08001e;
        public static final int vertical_layout=0x7f08000d;
    }
    public static final class layout {
        public static final int location_picker_view=0x7f030000;
        public static final int tag_view=0x7f030001;
    }
    public static final class menu {
        public static final int main_menu=0x7f070000;
        public static final int tag_menu=0x7f070001;
    }
    public static final class string {
        public static final int app_name=0x7f060000;
        public static final int app_name_version=0x7f060002;
        public static final int app_version=0x7f060001;
        public static final int cancel=0x7f060022;
        public static final int config_category_gps=0x7f060057;
        public static final int config_category_server=0x7f060050;
        /**  Preferences 
 Preferences 
         */
        public static final int config_category_view=0x7f060046;
        public static final int config_enableAntiAliasing_key=0x7f06004d;
        public static final int config_enableAntiAliasing_summary=0x7f06004f;
        public static final int config_enableAntiAliasing_title=0x7f06004e;
        public static final int config_gps_distance_key=0x7f060058;
        public static final int config_gps_distance_summary=0x7f06005a;
        public static final int config_gps_distance_title=0x7f060059;
        public static final int config_gps_interval_key=0x7f06005b;
        public static final int config_gps_interval_summary=0x7f06005d;
        public static final int config_gps_interval_title=0x7f06005c;
        public static final int config_password_key=0x7f060054;
        public static final int config_password_summary=0x7f060056;
        public static final int config_password_title=0x7f060055;
        public static final int config_showStats_key=0x7f060047;
        public static final int config_showStats_summary=0x7f060049;
        public static final int config_showStats_title=0x7f060048;
        public static final int config_showTolerance_key=0x7f06004a;
        public static final int config_showTolerance_summary=0x7f06004c;
        public static final int config_showTolerance_title=0x7f06004b;
        public static final int config_username_key=0x7f060051;
        public static final int config_username_summary=0x7f060053;
        public static final int config_username_title=0x7f060052;
        public static final int error_email_chooser_title=0x7f06001e;
        /**  ErrorMailer  
 ErrorMailer  
         */
        public static final int error_email_message=0x7f06001d;
        public static final int key=0x7f060024;
        public static final int link_mapfeatures=0x7f060026;
        public static final int location_button_no_location=0x7f060031;
        public static final int location_choose_radius=0x7f060029;
        public static final int location_coordinates_text=0x7f06002d;
        public static final int location_current_text=0x7f06002b;
        /**  Strings in LocationPicker 
 Strings in LocationPicker 
         */
        public static final int location_headline=0x7f060028;
        public static final int location_label_no_location=0x7f060032;
        public static final int location_last_text=0x7f06002a;
        public static final int location_lat_label=0x7f06002e;
        public static final int location_load_button=0x7f060030;
        public static final int location_lon_label=0x7f06002f;
        public static final int location_map_text=0x7f06002c;
        public static final int location_nan_message=0x7f060034;
        public static final int location_nan_title=0x7f060033;
        public static final int menu_add=0x7f060037;
        public static final int menu_append=0x7f06003a;
        public static final int menu_config=0x7f060038;
        public static final int menu_edit=0x7f060036;
        public static final int menu_erase=0x7f060039;
        public static final int menu_gps=0x7f06003c;
        public static final int menu_gps_follow=0x7f06003e;
        public static final int menu_gps_start_pause=0x7f06003d;
        public static final int menu_gps_stop=0x7f06003f;
        public static final int menu_gps_upload=0x7f060040;
        /**  Menu 
 Menu 
         */
        public static final int menu_move=0x7f060035;
        public static final int menu_save=0x7f060045;
        public static final int menu_tag=0x7f06003b;
        public static final int menu_transfer=0x7f060041;
        public static final int menu_transfer_download_current=0x7f060042;
        public static final int menu_transfer_download_other=0x7f060043;
        public static final int menu_transfer_upload=0x7f060044;
        public static final int no=0x7f060020;
        public static final int no_connection_message=0x7f06000d;
        public static final int no_connection_title=0x7f06000c;
        public static final int no_login_data_message=0x7f06000b;
        public static final int no_login_data_title=0x7f06000a;
        public static final int okay=0x7f060021;
        public static final int progress_download_message=0x7f060015;
        public static final int progress_message=0x7f060014;
        public static final int progress_title=0x7f060013;
        public static final int resume_last_activity_dialog_message=0x7f060004;
        /**  Dialogs 
 Dialogs 
         */
        public static final int resume_last_activity_dialog_title=0x7f060003;
        public static final int tag_menu_mapfeatures=0x7f060027;
        /**  Strings in TagEditor 
 Strings in TagEditor 
         */
        public static final int tag_title=0x7f060023;
        public static final int toast_empty_data=0x7f060018;
        public static final int toast_follow_gps_off=0x7f06001c;
        /**  Toaster 
 Toaster 
         */
        public static final int toast_no_changes=0x7f060016;
        public static final int toast_not_in_edit_range=0x7f060019;
        public static final int toast_save_done=0x7f06001a;
        public static final int toast_upload_success=0x7f060017;
        public static final int toast_waiting_for_gps=0x7f06001b;
        public static final int transfer_download_current_back=0x7f060009;
        public static final int transfer_download_current_dialog_message=0x7f060006;
        public static final int transfer_download_current_dialog_title=0x7f060005;
        public static final int transfer_download_current_download=0x7f060008;
        public static final int transfer_download_current_upload=0x7f060007;
        public static final int undefined_error_message=0x7f060011;
        public static final int undefined_error_sendbutton=0x7f060012;
        public static final int undefined_error_title=0x7f060010;
        public static final int value=0x7f060025;
        public static final int wrong_login_data_message=0x7f06000f;
        public static final int wrong_login_data_title=0x7f06000e;
        /**  Some generic labels 
 Some generic labels 
         */
        public static final int yes=0x7f06001f;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
