/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package de.blau.android;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int bridleway=0x7f06000f;
        public static final int building=0x7f060016;
        public static final int ccc_beige=0x7f060002;
        public static final int ccc_darkred=0x7f060001;
        public static final int ccc_ocher=0x7f060004;
        public static final int ccc_red=0x7f060000;
        public static final int ccc_white=0x7f060003;
        public static final int college=0x7f060018;
        public static final int commercial=0x7f06001c;
        public static final int cycleway=0x7f06000d;
        public static final int footway=0x7f06000e;
        public static final int forest=0x7f06001a;
        public static final int grey=0x7f060005;
        public static final int halt=0x7f060014;
        public static final int leisure=0x7f060017;
        public static final int motorway=0x7f060007;
        public static final int parking=0x7f060019;
        /**  
	<color name="unclassified">#FFFFFF</color>
	<color name="residential">#FFFFFF</color>
	<color name="living_street">#FFFFFF</color>
	<color name="service">#FFFFFF</color>

         */
        public static final int pedestrian=0x7f06000c;
        public static final int power=0x7f060015;
        public static final int primary=0x7f060009;
        public static final int retail=0x7f06001b;
        public static final int river=0x7f060011;
        public static final int secondary=0x7f06000a;
        public static final int station=0x7f060013;
        public static final int stroke=0x7f060006;
        public static final int tertiary=0x7f06000b;
        public static final int tracktype=0x7f060010;
        public static final int tram=0x7f060012;
        public static final int trunk=0x7f060008;
        public static final int water=0x7f06001d;
    }
    public static final class drawable {
        public static final int alert_dialog_icon=0x7f020000;
        public static final int menu_add=0x7f020001;
        public static final int menu_append=0x7f020002;
        public static final int menu_edit=0x7f020003;
        public static final int menu_erase=0x7f020004;
        public static final int menu_move=0x7f020005;
        public static final int menu_tag=0x7f020006;
        public static final int osm_logo=0x7f020007;
        /**  copied 
         */
        public static final int screen_background_black=0x7f020008;
        public static final int translucent_background=0x7f020009;
        public static final int transparent_background=0x7f02000a;
    }
    public static final class id {
        public static final int location_button_current=0x7f09000b;
        public static final int location_button_no_location=0x7f09000c;
        public static final int location_coordinates=0x7f090005;
        public static final int location_coordinates_layout=0x7f090006;
        public static final int location_current=0x7f090003;
        public static final int location_last=0x7f090002;
        public static final int location_lat_edit=0x7f090007;
        public static final int location_lon_edit=0x7f090008;
        public static final int location_map=0x7f090004;
        public static final int location_radius_seeker=0x7f09000a;
        public static final int location_radius_text=0x7f090009;
        public static final int location_type=0x7f090000;
        public static final int location_type_group=0x7f090001;
        public static final int menu_add=0x7f09000f;
        public static final int menu_append=0x7f090012;
        public static final int menu_confing=0x7f09001b;
        public static final int menu_edit=0x7f090010;
        public static final int menu_erase=0x7f090013;
        public static final int menu_gps_follow=0x7f090015;
        public static final int menu_gps_start_pause=0x7f090014;
        public static final int menu_gps_stop=0x7f090016;
        public static final int menu_gps_upload=0x7f090017;
        public static final int menu_move=0x7f09000e;
        public static final int menu_save=0x7f09001c;
        public static final int menu_tag=0x7f090011;
        public static final int menu_transfer_download_current=0x7f090018;
        public static final int menu_transfer_download_other=0x7f090019;
        public static final int menu_transfer_upload=0x7f09001a;
        public static final int tag_menu_mapfeatures=0x7f09001d;
        public static final int vertical_layout=0x7f09000d;
    }
    public static final class layout {
        public static final int location_picker_view=0x7f030000;
        public static final int tag_view=0x7f030001;
    }
    public static final class menu {
        public static final int main_menu=0x7f080000;
        public static final int tag_menu=0x7f080001;
    }
    public static final class raw {
        public static final int bergen_quad=0x7f050000;
        public static final int blau=0x7f050001;
        public static final int blau_horizontal=0x7f050002;
        public static final int empty=0x7f050003;
        public static final int hamburg=0x7f050004;
        public static final int hamburg_gzip=0x7f050005;
        public static final int quito_quad=0x7f050006;
        public static final int ratio_test=0x7f050007;
        public static final int schulterblatt_localhost=0x7f050008;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int app_name_version=0x7f070002;
        public static final int app_version=0x7f070001;
        public static final int cancel=0x7f070022;
        public static final int config_category_gps=0x7f070057;
        public static final int config_category_server=0x7f070050;
        /**  Preferences 
         */
        public static final int config_category_view=0x7f070046;
        public static final int config_enableAntiAliasing_key=0x7f07004d;
        public static final int config_enableAntiAliasing_summary=0x7f07004f;
        public static final int config_enableAntiAliasing_title=0x7f07004e;
        public static final int config_gps_distance_key=0x7f070058;
        public static final int config_gps_distance_summary=0x7f07005a;
        public static final int config_gps_distance_title=0x7f070059;
        public static final int config_gps_interval_key=0x7f07005b;
        public static final int config_gps_interval_summary=0x7f07005d;
        public static final int config_gps_interval_title=0x7f07005c;
        public static final int config_password_key=0x7f070054;
        public static final int config_password_summary=0x7f070056;
        public static final int config_password_title=0x7f070055;
        public static final int config_showStats_key=0x7f070047;
        public static final int config_showStats_summary=0x7f070049;
        public static final int config_showStats_title=0x7f070048;
        public static final int config_showTolerance_key=0x7f07004a;
        public static final int config_showTolerance_summary=0x7f07004c;
        public static final int config_showTolerance_title=0x7f07004b;
        public static final int config_username_key=0x7f070051;
        public static final int config_username_summary=0x7f070053;
        public static final int config_username_title=0x7f070052;
        public static final int error_email_chooser_title=0x7f07001e;
        /**  ErrorMailer  
         */
        public static final int error_email_message=0x7f07001d;
        public static final int key=0x7f070024;
        public static final int link_mapfeatures=0x7f070026;
        public static final int location_button_no_location=0x7f070031;
        public static final int location_choose_radius=0x7f070029;
        public static final int location_coordinates_text=0x7f07002d;
        public static final int location_current_text=0x7f07002b;
        /**  Strings in LocationPicker 
         */
        public static final int location_headline=0x7f070028;
        public static final int location_label_no_location=0x7f070032;
        public static final int location_last_text=0x7f07002a;
        public static final int location_lat_label=0x7f07002e;
        public static final int location_load_button=0x7f070030;
        public static final int location_lon_label=0x7f07002f;
        public static final int location_map_text=0x7f07002c;
        public static final int location_nan_message=0x7f070034;
        public static final int location_nan_title=0x7f070033;
        public static final int menu_add=0x7f070037;
        public static final int menu_append=0x7f07003a;
        public static final int menu_config=0x7f070038;
        public static final int menu_edit=0x7f070036;
        public static final int menu_erase=0x7f070039;
        public static final int menu_gps=0x7f07003c;
        public static final int menu_gps_follow=0x7f07003e;
        public static final int menu_gps_start_pause=0x7f07003d;
        public static final int menu_gps_stop=0x7f07003f;
        public static final int menu_gps_upload=0x7f070040;
        /**  Menu 
         */
        public static final int menu_move=0x7f070035;
        public static final int menu_save=0x7f070045;
        public static final int menu_tag=0x7f07003b;
        public static final int menu_transfer=0x7f070041;
        public static final int menu_transfer_download_current=0x7f070042;
        public static final int menu_transfer_download_other=0x7f070043;
        public static final int menu_transfer_upload=0x7f070044;
        public static final int no=0x7f070020;
        public static final int no_connection_message=0x7f07000d;
        public static final int no_connection_title=0x7f07000c;
        public static final int no_login_data_message=0x7f07000b;
        public static final int no_login_data_title=0x7f07000a;
        public static final int okay=0x7f070021;
        public static final int progress_download_message=0x7f070015;
        public static final int progress_message=0x7f070014;
        public static final int progress_title=0x7f070013;
        public static final int resume_last_activity_dialog_message=0x7f070004;
        /**  Dialogs 
         */
        public static final int resume_last_activity_dialog_title=0x7f070003;
        public static final int tag_menu_mapfeatures=0x7f070027;
        /**  Strings in TagEditor 
         */
        public static final int tag_title=0x7f070023;
        public static final int toast_empty_data=0x7f070018;
        public static final int toast_follow_gps_off=0x7f07001c;
        /**  Toaster 
         */
        public static final int toast_no_changes=0x7f070016;
        public static final int toast_not_in_edit_range=0x7f070019;
        public static final int toast_save_done=0x7f07001a;
        public static final int toast_upload_success=0x7f070017;
        public static final int toast_waiting_for_gps=0x7f07001b;
        public static final int transfer_download_current_back=0x7f070009;
        public static final int transfer_download_current_dialog_message=0x7f070006;
        public static final int transfer_download_current_dialog_title=0x7f070005;
        public static final int transfer_download_current_download=0x7f070008;
        public static final int transfer_download_current_upload=0x7f070007;
        public static final int undefined_error_message=0x7f070011;
        public static final int undefined_error_sendbutton=0x7f070012;
        public static final int undefined_error_title=0x7f070010;
        public static final int value=0x7f070025;
        public static final int wrong_login_data_message=0x7f07000f;
        public static final int wrong_login_data_title=0x7f07000e;
        /**  Some generic labels 
         */
        public static final int yes=0x7f07001f;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
